version: "3.8"

services:
  ollama:
    build:
      context: ./external_service
      dockerfile: Dockerfile
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app  # Mount the current directory to /app inside the container

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    restart: unless-stopped

    volumes:
      - .:/app  # Mount the current directory to /app inside the container

  # prometheus:
  #     image: prom/prometheus:latest
  #     container_name: prometheus
  #     ports:
  #       - "9090:9090"
  #     volumes:
  #       - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     command:
  #       - '--config.file=/etc/prometheus/prometheus.yml'
  # alertmanager:
  #   image: prom/alertmanager:latest
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   command:
  #     - '--config.file=/etc/alertmanager/alertmanager.yml'
  #   networks:
  #     - your_network

volumes:
  ollama:
