apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-west1-docker.pkg.dev/secure-project-tutorial/dasc-docker/frontend:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "500m"  # Minimum CPU request
            memory: "256Mi"  # Minimum memory request
          limits:
            cpu: "1000m"  # Maximum CPU limit
            memory: "512Mi"  # Maximum memory limit
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
